apiVersion: v1
kind: Namespace
metadata:
  annotations:
    package-operator.run/phase: namespaces
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx
