apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  creationTimestamp: null
  name: nginx-ingress
spec:
  availabilityProbes:
  - probes:
    - condition:
        status: "True"
        type: Available
    - fieldsEqual:
        fieldA: .status.updatedReplicas
        fieldB: .status.replicas
    selector:
      kind:
        group: apps
        kind: Deployment
  - probes:
    - condition:
        status: "True"
        type: Complete
    selector:
      kind:
        group: batch
        kind: Job
  config:
    openAPIV3Schema:
      properties:
        config:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      type: object
  filter: {}
  images: null
  phases:
  - name: namespaces
  - name: rbac
  - name: deploy
  - name: publish
  - name: other
  scopes:
  - Cluster
test:
  template:
  - name: cluster-scope
    context:
      config:
        config:
          allow-snippet-annotations: "false"
      package:
        metadata:
          name: test
      environment: {}
