apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud
  annotations:
    package-operator.run/phase: deploy
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: nextcloud
  type: ClusterIP