apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  creationTimestamp: null
  name: collabora
spec:
  phases:
  - name: deploy
  config:
    openAPIV3Schema:
      properties:
        hostname:
          type: string
        clusterIssuer:
          type: string
        extra_params:
          default: ""
          type: string
      required:
      - hostname
      - clusterIssuer
      type: object
  filter: {}
  images:
  - name: collabora
    image: docker.io/collabora/code:25.04.5.2.1
  scopes:
  - Namespaced
test:
  kubeconform:
    kubernetesVersion: v1.28.2
  template:
  - name: hostdir
    context:
      config:
        storage:
          hostDir: {}
        hostname: cloud.package-operator.run
        clusterIssuer: letsencrypt-prod
        extra_params: ' --o:remote_font_config.url=https://cloud.package-operator.run/apps/richdocuments/settings/fonts.json'
      package:
        metadata:
          name: test
          namespace: test-ns