apiVersion: v1
kind: Service
metadata:
  name: espocrm
  labels:
    app: espocrm
  annotations:
    package-operator.run/phase: deploy
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: espocrm
  type: ClusterIP